[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
authors = ["Oliver Chalk"]
edition = "2021"

[workspace.dependencies]
shared = { path = "./crates/shared" }
thiserror = "1.0.40"

[profile.release]
codegen-units = 1
debug = true
opt-level = 3
overflow-checks = true
