[package]
name = "jack"
version = "0.1.0"
edition = "2021"
authors.workspace = true

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
strum = { version = "0.27.2", features = ["derive"] }
